2025-02-08 15:30:10,654 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:30:10,658 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:30:11,022 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:30:11,298 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:31:40,343 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:31:40,345 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:31:40,378 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:31:40,657 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:32:21,386 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153010.db
2025-02-08 15:32:21,391 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:32:21,392 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:32:35,459 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_150000.db
2025-02-08 15:32:35,461 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:32:35,462 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:06,401 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153010.db
2025-02-08 15:33:06,405 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:33:06,406 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:12,588 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_142420.db
2025-02-08 15:33:12,595 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:33:12,595 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:33:58,103 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:33:58,106 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:33:58,453 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:33:58,837 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:34:37,536 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:34:37,544 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:34:37,575 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:34:37,860 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:34:49,962 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153358.db
2025-02-08 15:34:49,968 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:34:49,969 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:35:20,068 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153437.db
2025-02-08 15:35:20,070 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:35:20,071 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:35:25,202 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153358.db
2025-02-08 15:35:25,207 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:35:25,207 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
2025-02-08 15:38:05,471 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:38:05,486 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:38:05,780 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:38:06,074 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:38:30,740 - app - DEBUG - Intentando crear un backup antes de la actualización...
2025-02-08 15:38:30,761 - app - DEBUG - Leyendo el archivo Excel: uploads\notas_9A_.xlsx
2025-02-08 15:38:30,797 - app - DEBUG - Procesando filas del archivo Excel...
2025-02-08 15:38:31,070 - app - DEBUG - Datos actualizados correctamente.
2025-02-08 15:38:43,708 - app - DEBUG - Restaurando la base de datos desde el backup: backups\backup_20250208_153830.db
2025-02-08 15:38:43,711 - app - DEBUG - Reiniciando la sesión de SQLAlchemy...
2025-02-08 15:38:43,712 - app - ERROR - Error al restaurar el backup: 'Session' object has no attribute 'remove'
